# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('score', models.CharField(default='0-0', max_length=10)),
                ('score1', models.IntegerField(blank=True, null=True)),
                ('score2', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=100, null=True)),
                ('stage', models.CharField(blank=True, max_length=100, null=True)),
                ('round', models.IntegerField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('vod_link', models.CharField(blank=True, max_length=200, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='csapp/layers')),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('prize', models.IntegerField(blank=True, null=True)),
                ('groups', models.BooleanField(default=False)),
                ('about', models.TextField(blank=True, null=True)),
                ('format', models.TextField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='csapp/tournaments')),
                ('presenters', models.ManyToManyField(related_name='presenters', to='csapp.Player')),
                ('teams', models.ManyToManyField(related_name='teams', to='csapp.Team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csapp.Team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='formerteams',
            field=models.ManyToManyField(related_name='fteams', to='csapp.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csapp.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t1', to='csapp.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t2', to='csapp.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csapp.Tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='win', to='csapp.Team'),
        ),
    ]
