# Generated by Django 2.0.1 on 2018-09-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csapp', '0003_player_current_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_colors',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
