# Generated by Django 2.0.1 on 2018-09-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csapp', '0004_auto_20180926_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='csapp/players'),
        ),
    ]
