# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class1', models.CharField(choices=[('MAGE', 'Mage'), ('WARRIOR', 'Warrior'), ('WARLOCK', 'Warlock'), ('HUNTER', 'Hunter'), ('PRIEST', 'Priest'), ('DRUID', 'Druid'), ('ROGUE', 'Rogue'), ('PALADIN', 'Paladin'), ('SHAMAN', 'Shaman')], max_length=20)),
                ('class2', models.CharField(choices=[('MAGE', 'Mage'), ('WARRIOR', 'Warrior'), ('WARLOCK', 'Warlock'), ('HUNTER', 'Hunter'), ('PRIEST', 'Priest'), ('DRUID', 'Druid'), ('ROGUE', 'Rogue'), ('PALADIN', 'Paladin'), ('SHAMAN', 'Shaman')], max_length=20)),
                ('winner', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.CharField(max_length=10)),
                ('format', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=100)),
                ('finished', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsapp.Player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='hsapp.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='hsapp.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Tournament'),
        ),
        migrations.AddField(
            model_name='game',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsapp.Match'),
        ),
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pl1', to='hsapp.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pl2', to='hsapp.Player'),
        ),
    ]
