# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0005_auto_20170815_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='hsapp.Player'),
        ),
    ]
