# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0009_auto_20170816_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
