# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0012_auto_20170820_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='groups',
            field=models.BooleanField(default=False),
        ),
    ]
