# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0013_tournament_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
