# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0015_auto_20170827_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.TextField(blank=True, null=True),
        ),
    ]
