# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0016_auto_20170827_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hsapp/tournaments'),
        ),
    ]
