# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0018_card_deck_deckset'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='attack',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='health',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='inspire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='taunt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='CLASS',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='artist',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_set',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardtype',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='players', to='hsapp.Player'),
        ),
    ]
