# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0020_auto_20170829_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='archetype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='deck_class',
            field=models.CharField(blank=True, choices=[('MAGE', 'Mage'), ('WARRIOR', 'Warrior'), ('WARLOCK', 'Warlock'), ('HUNTER', 'Hunter'), ('PRIEST', 'Priest'), ('DRUID', 'Druid'), ('ROGUE', 'Rogue'), ('PALADIN', 'Paladin'), ('SHAMAN', 'Shaman')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hsapp/decks/'),
        ),
        migrations.AddField(
            model_name='deck',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Player'),
        ),
        migrations.AddField(
            model_name='deck',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Tournament'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(blank=True, to='hsapp.Card'),
        ),
        migrations.AlterField(
            model_name='game',
            name='class1',
            field=models.CharField(choices=[('MAGE', 'Mage'), ('WARRIOR', 'Warrior'), ('WARLOCK', 'Warlock'), ('HUNTER', 'Hunter'), ('PRIEST', 'Priest'), ('DRUID', 'Druid'), ('ROGUE', 'Rogue'), ('PALADIN', 'Paladin'), ('SHAMAN', 'Shaman')], max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='class2',
            field=models.CharField(choices=[('MAGE', 'Mage'), ('WARRIOR', 'Warrior'), ('WARLOCK', 'Warlock'), ('HUNTER', 'Hunter'), ('PRIEST', 'Priest'), ('DRUID', 'Druid'), ('ROGUE', 'Rogue'), ('PALADIN', 'Paladin'), ('SHAMAN', 'Shaman')], max_length=50),
        ),
    ]
