# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0021_auto_20170905_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='title',
        ),
    ]
