# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0022_remove_deck_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
