# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0023_match_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('article', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=300, null=True)),
                ('players', models.ManyToManyField(to='hsapp.Player')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hsapp.Tournament')),
            ],
        ),
    ]
