# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0024_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
