# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0026_match_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='prize',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
