# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0031_tournament_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='format',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
