# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0032_auto_20171014_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
