# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0033_auto_20171014_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 14, 11, 30, 17, 610939, tzinfo=utc)),
        ),
    ]
