# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0037_auto_20171105_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
