# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 17:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0038_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 5, 17, 9, 35, 423820, tzinfo=utc)),
        ),
    ]
