# Generated by Django 2.0.1 on 2018-08-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0041_auto_20171105_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_set',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
