# Generated by Django 2.0.1 on 2018-10-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0043_tournament_official_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to='hsapp.Player'),
        ),
    ]
