# Generated by Django 2.1.2 on 2018-10-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0044_auto_20181022_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='collectible',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
